// <auto-generated />
namespace Asp_Web_Lib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Book_ISBN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Book_ISBN));
        
        string IMigrationMetadata.Id
        {
            get { return "202411241141227_Book_ISBN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
