//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_Web_Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asp_Web_Lib.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Twoje konto nie zostało jeszcze potwierdzone przez administratora..
        /// </summary>
        public static string AccountConfirmationError {
            get {
                return ResourceManager.GetString("AccountConfirmationError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Konta oczekujące na zatwierdzenie.
        /// </summary>
        public static string AccountsForAproval {
            get {
                return ResourceManager.GetString("AccountsForAproval", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Status konta.
        /// </summary>
        public static string AccountStatus {
            get {
                return ResourceManager.GetString("AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Akcje.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień hasło.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Konta oczekujące na potwierdzenie.
        /// </summary>
        public static string ConfirmAcconutLabel {
            get {
                return ResourceManager.GetString("ConfirmAcconutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zweryfikuj konto.
        /// </summary>
        public static string ConfirmAccountBtn {
            get {
                return ResourceManager.GetString("ConfirmAccountBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Liczba dni przedłużenia/wypożyczenia książki.
        /// </summary>
        public static string ExtensionDays {
            get {
                return ResourceManager.GetString("ExtensionDays", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia biblioteki.
        /// </summary>
        public static string LibrarySettings {
            get {
                return ResourceManager.GetString("LibrarySettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kwota naliczana za dzień przetrzymania książki.
        /// </summary>
        public static string LoanAmount {
            get {
                return ResourceManager.GetString("LoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyloguj się.
        /// </summary>
        public static string Log_off {
            get {
                return ResourceManager.GetString("Log_off", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaloguj się.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarządzaj autorami.
        /// </summary>
        public static string Manage_authors {
            get {
                return ResourceManager.GetString("Manage_authors", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarządzaj książkami.
        /// </summary>
        public static string Manage_books {
            get {
                return ResourceManager.GetString("Manage_books", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarządzaj kategoriami.
        /// </summary>
        public static string Manage_categories {
            get {
                return ResourceManager.GetString("Manage_categories", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarządzaj uprawnieniami.
        /// </summary>
        public static string Manage_permissions {
            get {
                return ResourceManager.GetString("Manage_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarządzaj wydawcami.
        /// </summary>
        public static string Manage_publishers {
            get {
                return ResourceManager.GetString("Manage_publishers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarządzaj tagami.
        /// </summary>
        public static string Manage_tags {
            get {
                return ResourceManager.GetString("Manage_tags", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarządzaj rolami.
        /// </summary>
        public static string ManageRoles {
            get {
                return ResourceManager.GetString("ManageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maksymalna liczba wypożyczeń.
        /// </summary>
        public static string MaxBorrowedBooks {
            get {
                return ResourceManager.GetString("MaxBorrowedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maksymalna liczba przedłużeń.
        /// </summary>
        public static string MaxExtensionNumber {
            get {
                return ResourceManager.GetString("MaxExtensionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maksymalna liczba książek w kolejce.
        /// </summary>
        public static string MaxWaitingBooks {
            get {
                return ResourceManager.GetString("MaxWaitingBooks", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Oczekuje na potwierdzenie.
        /// </summary>
        public static string PendingForAproval {
            get {
                return ResourceManager.GetString("PendingForAproval", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarejestruj się.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Role.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
    }
}
